### ISSUE TITLE
django 4.0 compatibility

### ISSUE THREAD

**Issue by felixrindt** [safwanrahman/django-webpush#101]
Trying a django [4.0a1](https://docs.djangoproject.com/en/dev/releases/4.0/) project with webpush leads to 
`ImportError: cannot import name 'url' from 'django.conf.urls'`
in `webpush/urls.py`. `url` is deprecated and path should be used instead, which is already the case in this particular file as far as I see.

**Comment by clearminds** [comment]
https://github.com/safwanrahman/django-webpush/pull/105 fixes this
