### ISSUE TITLE
Request body in save_info view is bytes object

### ISSUE THREAD

**Issue by arogachev** [safwanrahman/django-webpush#11]
During subscribing I get this error:

> TypeError: the JSON object must be str, not 'bytes'

This is because of this line in `save_info` view:

```python
post_data = json.loads(request.body)
```

After debugging I have found that `request.body` is bytes object, not simple string.

To fix that we need to convert it to string:

```python
post_data = json.loads(request.body.decode(encoding='utf-8'))
```

However I'm not sure, maybe it can be both string and bytes depending on different circumstances.

In this case we can explicitly check for a type before converting.

```python
request_body = request.body
if isinstance(request_body, bytes):
    request_body = request_body.decode(encoding='utf-8')
post_data = json.loads(request.body)
```

But it would be better to find the reason why `request.body` can be a `bytes` object.

Some details: I use Python 3.5.2 and Django 1.9.5 in my project. Error happens in both Mozilla Firefox 49.0.1 and Chrome 53.0.2785.143 m browsers (these are the latest versions at the moment).

I tested it with the latest extension's code.

As a current workaround I overrided `save_info` view and applied this fix and also overrided `save_webpush_info` url, pointed it to custom view and placed it above extensions's urls:

```python
url(r'^webpush/', include('webpush.urls')),
```

**Comment by safwanrahman** [comment]
Yap. In python 3.x, by default it is byte rather than string. In python 2.x, its string.
I dont know ``python 3.x`` and I think the approach you have taken, is suitable for both python 2.x and python 3.x

**Comment by arogachev** [comment]
I investigated issue more deeply. It's not about `request.body`, it's always a [byte string](https://docs.djangoproject.com/el/1.10/ref/request-response/#django.http.HttpRequest.body). The reason is `json.loads()` in Python 3 allows only strings: 

```python
if not isinstance(s, str):
    raise TypeError('the JSON object must be str, not {!r}'.format(s.__class__.__name__))
```

Check this [SO question](http://stackoverflow.com/a/29514222/4323648) for example:

> The request body, `request.body`, is a byte string. In Python 3, `json.loads()` will only accept a unicode string, so you must decode `request.body` before passing it to `json.loads()`.
> 
> ```python
> body_unicode = request.body.decode('utf-8')
> body_data = json.loads(body_unicode)
> ```
> 
> In Python 2, `json.loads` will accept a unicode string or a byte sting, so the decode step is not necessary.

So decoding to unicode string will work for both Python 2 and 3 (even for version 2 is not required), also this is shorter and more elegant solution in my opinion.

But it will be better to have some tests.
