### ISSUE TITLE
Support for IOS 16.4 web push notifications?

### ISSUE THREAD

**Issue by DartLazer** [safwanrahman/django-webpush#121]
Is there a way to implement we push notifications now that IOS 16.4 officially supports it?

**Comment by azmeuk** [comment]
For the record there was a discussion about this in #116

**Comment by DartLazer** [comment]
Yes it all seems to be working fine on my iOS devices. Great work thanks @azmeuk

**Comment by azmeuk** [comment]
After a few tests I can confirm this library works well with safari installed as webapp on iphones.

**Comment by DartLazer** [comment]
Thank you for your great work!
