### ISSUE TITLE
IOS 16.4 Support Approach(Solved)

### ISSUE THREAD

**Issue by fabianbrn** [safwanrahman/django-webpush#123]
Hey, can you integrate this?
https://taoshu.in/web/push-on-ios.html

**Comment by azmeuk** [comment]
Duplicate of #121

**Comment by fabianbrn** [comment]
Thats not the same, the Link is the Solution, it works with APNS. It would be great, if implemented in this module

**Comment by fabianbrn** [comment]
It works now:)

**Comment by azmeuk** [comment]
What do you mean?
