### ISSUE TITLE
Errors When Sending Notifications

### ISSUE THREAD

**Issue by raniaCht** [safwanrahman/django-webpush#129]
I am facing issues with django-webpush related to sending push notifications. Unfortunately, I'm not certain about the specific conditions or triggers causing these errors. The errors include HTTP responses like:

- WebPushException: Push failed: 406 Not Acceptable
- WebPushException: Push failed: 500 Internal Server Error                                           
- WebPushException: Push failed: 502 Bad Gateway
- Bad Request: /webpush/save_information 

**Environment:**
- Django Version: 4.1.1
- django_webpush Version: 0.3.4

Thank you for your help.

**Comment by safwanrahman** [comment]
Without proper information, it is quite difficult to answer this. Moreover, it is better to ask question on stackoverflow. Thanks

**Comment by raniaCht** [comment]
Please delete the issue
