### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation (validators.py)

### ISSUE THREAD

**Issue by arogachev** [safwanrahman/django-webpush#14]
This error is shown after running `pip install django-webpush`:

> Sorry: TabError: inconsistent use of tabs and spaces in indentation (validators.py, line 14)

**Comment by safwanrahman** [comment]
So the ``validators.py`` is useless. We do not use it now. while making the initial release, i added, later forget to remove that. I am going to remove that
Thanks

**Comment by safwanrahman** [comment]
Fixed with  	1fc940e
