### ISSUE TITLE
Trying to load models in __init__ fails in 1.10

### ISSUE THREAD

**Issue by skorokithakis** [safwanrahman/django-webpush#30]
Django 1.10 fails with an "Apps are not ready" error when trying to load webpush because it's trying to load its models in `__init__.py` but models haven't been loaded yet. The project should probably be restructured so it either uses lazy loading or doesn't load anything in `__init__.py`.

**Comment by jamaalscarlett** [comment]
Are you using the latest from master, or installing from pypi?  This should be fixed in the repo

**Comment by skorokithakis** [comment]
I was using both. It's trying to import utils, which imports models, which fails in 1.10.

**Comment by safwanrahman** [comment]
Oh! I did not notice about it. Going to work on this in this weekend.
Thanks @skorokithakis for the report.

**Comment by safwanrahman** [comment]
@skorokithakis I have tested this in my local environment. Can you please recreate your virtualenv and install directly from this repository? I think your virtualenv is using the old version. 
``pip install https://github.comafwanrahman/django-webpush/archive/master.zip``
I am going to push the latest release to pypy within this week

**Comment by safwanrahman** [comment]
@skorokithakis A new release ``0.2.1`` has been made. Can you please check by installing it and let me know whether it fixes the issue or not?

**Comment by skorokithakis** [comment]
Yep, `0.2.1` works fine, thank you!
