### ISSUE TITLE
Exception Value:	 Invalid block tag on line 17: 'webush_button'. Did you forget to register or load this tag?

### ISSUE THREAD

**Issue by makelove** [safwanrahman/django-webpush#42]
Your document is not correct!
```html
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
    {% load webpush_notifications %}
    {% webpush_header %}
{#    {{ webpush_header() }}#}
</head>
<body>
<div id="webpush">
    <span>notifications</span>
    {% webush_button %}
{#    {{ webush_button() }}#}
</div>
</body>
```

could you write down your document in more specific detail ?
Django==2.0.6
django-webpush==0.2.4

**Comment by safwanrahman** [comment]
Hi @makelove Can you remove completely the jinja tag and try? Its registered 
https://github.com/safwanrahman/django-webpush/blob/3913753bd60007bdfd23cedcf381e629f3bea55a/webpush/templatetags/webpush_notifications.py#L19

**Comment by makelove** [comment]
{% load webpush_notifications %}
    {% webpush_header %}

**Comment by makelove** [comment]
{% load webpush_notifications %}
{% webpush_header %}
is working
but
{% webush_button %}
will raise that error

**Comment by safwanrahman** [comment]
Can you please post the full error log?

**Comment by makelove** [comment]
> TemplateSyntaxError at /chat/
Invalid block tag on line 17: 'webush_button'. Did you forget to register or load this tag?
Request Method:	GET
Request URL:	http://127.0.0.1:8000/chat/
Django Version:	2.0.6
Exception Type:	TemplateSyntaxError
Exception Value:	
Invalid block tag on line 17: 'webush_button'. Did you forget to register or load this tag?
Exception Location:	/Users/play/Test测试/django-example-channels/env/lib/python3.6/site-packages/django/template/base.py in invalid_block_tag, line 539
Python Executable:	/Users/play/Test测试/django-example-channels/env/bin/python3.6
Python Version:	3.6.4
Python Path:	
['/Users/play/Test测试/channels/mysite',
 '/Users/play/Test测试/channels/mysite',
 '/Users/play/Test测试/django-example-channels/env/lib/python36.zip',
 '/Users/play/Test测试/django-example-channels/env/lib/python3.6',
 '/Users/play/Test测试/django-example-channels/env/lib/python3.6/lib-dynload',
 '/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6',
 '/Users/play/Test测试/django-example-channels/env/lib/python3.6/site-packages']
Server time:	Wed, 20 Jun 2018 12:48:12 +0000

**Comment by safwanrahman** [comment]
Oh! It was a typo!
it should be `{% webpush_button %}` not `{% webush_button %}

**Comment by safwanrahman** [comment]
@makelove could you solve it?

**Comment by makelove** [comment]
yes,Thank you
