### ISSUE TITLE
send_notification - public method

### ISSUE THREAD

**Issue by rjuppa** [safwanrahman/django-webpush#45]
There is missing a public method to send a notification to a single subcription.

Why it is needed?
- a user wants to send notification 3x times a day
  - morning to phone
  - afternoon to desktop
  - evening to tablet

Another problem with sending a notification to all user devices is when sending failed the loop is interrupted. That's why I would like to have better control over the process. 
 - a single subscription
 - queryset of subscriptions

**Comment by rjuppa** [comment]
https://gist.github.com/rjuppa/da35c38b6a5fd208df542f0cc6649f97

**Comment by safwanrahman** [comment]
I think you have implemented it in #47
