### ISSUE TITLE
JS files should be loaded from main app static/js

### ISSUE THREAD

**Issue by rjuppa** [safwanrahman/django-webpush#46]
Both JS files: 
`serviceworker.js`
`webpush.js`

 should be loaded from main app static/js rather then django_webpush app,
because they need to be customized.

A user can include them like jquery file or so. (just extend readme.md)

**Comment by safwanrahman** [comment]
You can customize them easily
just create another directory named `webpush` in your static folder and overwrite the filename to load your `webpush.js` and others.
