### ISSUE TITLE
KeyError: 'endpoint' when using admin interface to send notification

### ISSUE THREAD

**Issue by gnalbandian** [safwanrahman/django-webpush#50]
Hi, I have installed the package and generated the needed keys. I subscribed myself to receive notifications with an account without issues up till then.

When I log to the django admin interface and try to send a message to test if it works I get the following error.

` File "/home/socialapp/deepmetricsapps/NuevocentroShopping/lib/python3.5/site-packages/webpush/utils.py", line 71, in _process_subscription_info
    endpoint = subscription_data.pop("endpoint")
KeyError: 'endpoint'
`

Is this package still working? or am I doing something wrong?
I am using Django 2.0+ with gunicorn and nginx as reverse proxy. I subscribed to the service using chrome 70+

**Comment by chris542** [comment]
You need to change this in `admin.py`


```
for device in queryset:
   #from this
   result.append(_send_notification(device, json.dumps(payload), 0))
   #to this
   result.append(_send_notification(device.subscription, json.dumps(payload), 0))
```

**Comment by safwanrahman** [comment]
Thanks for the report. Sorry it took so long to make a small fix!
