### ISSUE TITLE
Subscriptions expiring

### ISSUE THREAD

**Issue by mkaluza** [safwanrahman/django-webpush#51]
Hi!
I've got a problem - some time after subscribing I can't send messages to subscibers anymore. It seems something has expired and I don't know if I'm doing something wrong.

I've found this: https://serviceworke.rs/push-subscription-management_service-worker_doc.html and the service worker included here doesn't seem to handle pushsubscriptionchange event.

Is there a way to make subscriptions persist longer? Or is it simply not implemented yet?

**Comment by safwanrahman** [comment]
> Is there a way to make subscriptions persist longer? Or is it simply not implemented yet?

It solely depends on the browser vendors! We can not do anything! I have made some fixes in 09996c0 that will remove the expired subscription. Thanks!
