### ISSUE TITLE
Cannot import WebPushException or send_single_notification

### ISSUE THREAD

**Issue by divonelnc** [safwanrahman/django-webpush#53]
When I try to use the third option (with fine grain control), the line `from webpush import WebPushException, send_single_notification` is not working. 
Was the option removed?

**Comment by chris542** [comment]
I don't see send_single_notification option in utils.py

Probably it's been removed.

**Comment by safwanrahman** [comment]
Sorry for the bad documentation. it has been fixed by  09996c0
