### ISSUE TITLE
change {% webpush_button %}

### ISSUE THREAD

**Issue by haditabarzad** [safwanrahman/django-webpush#54]
hi
I am in a situation changing the appearance of webpush_button. I dont want to change webpush package in my project. Is there a way to change it in my template? for example I dont want a button, instead I want a <a></a> with specific class. How should I do this?

thanks

**Comment by safwanrahman** [comment]
@haditabarzad I think you can create a template named `webpush_button.html` and put it in your template directory. It will overwrite the template which this package provides!
https://github.com/safwanrahman/django-webpush/blob/master/webpush/templates/webpush_button.html

**Comment by aliir74** [comment]
Hi @safwanrahman, I've tried your suggestion, but unfortunately, It didn't work. Do you have other ideas for changing the text or design of the push button?
