### ISSUE TITLE
Use a local ip address instead of a ngrok?

### ISSUE THREAD

**Issue by at-land** [safwanrahman/django-webpush#58]
Use a local ip address instead of a ngrok?
Hi thanks for the great work.

Can I dispense with ngrok?
I was asking how I could run the service via a local IP address
Eg on an internal network

router 10.10.1.1
// me : https://10.10.1.2
//pc2: 10.10.1.3

I want to communicate this way
iam use https from django ssl
but not working
thanks.

**Comment by marauder37** [comment]
What does "not working" mean?

**Comment by safwanrahman** [comment]
@at-land You can not get the push notification permission without using `https`. With IP, you can not use `https`. So better to use ngrok.

**Comment by safwanrahman** [comment]
It seems like now `127.0.0.1` works in most of the browser.
