### ISSUE TITLE
Version 0.3.0 requires pywebpush 1.6.0 but the code uses more recent features

### ISSUE THREAD

**Issue by ZeWaren** [safwanrahman/django-webpush#65]
The current release (version 0.3.0) requires `pywebpush` 1.6.0.

When sending a notification, exceptions of type `WebPushException` are caught and their response field is investigated 
https://github.com/safwanrahman/django-webpush/blob/09996c003562d49713140709819744ad02eaddc4/webpush/utils.py#L50
However, this field was added later in `pywebpush`.

Consequence: sending a notification to non-existent endpoint triggers a crash.

`pywebpush` should be updated.

**Comment by safwanrahman** [comment]
oops! Thanks for noticing!
I totally forgot about it. I will update it tomorrow and make another release. Thanks a lot!

**Comment by safwanrahman** [comment]
Sorry for taking long to fix it. Fixed it in `3.0.1`
