### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by kintawer** [safwanrahman/django-webpush#71]
I try follow all steps in read.me but nothing not working.
1. added installed_apps
2. added urlpatterns
3. manage.py migrate
4. get WEBPUSH_SETTINGS = { "VAPID_PUBLIC_KEY": "xxx", "VAPID_PRIVATE_KEY": "xxx", "VAPID_ADMIN_EMAIL": "test@test.com"
} from  this link https://web-push-codelab.glitch.me
5. try to use it:
![image](https://user-images.githubusercontent.com/24816975/63029598-828cbf00-beb9-11e9-87dc-6c24d43b8803.png)
6. nothing in my browser... 

So, what i need to do this work?

**Comment by safwanrahman** [comment]
I think you need to read the documentation better. If you do not use the template tag and register your browser, how do it even work?

**Comment by kintawer** [comment]
> I think you need to read the documentation better. If you do not use the template tag and register your browser, how do it even work?

So, I added templates button and header
Then click to subscribe button that create new record into DB
Thereafter I repeat scenario of 5th mark in my first message and i get this error:
 ```python
TypeError                                 Traceback (most recent call last)
<ipython-input-6-9159af5b8c6e> in <module>()
----> 1 send_notification_to_user(user=user, payload={"body": "test", "head": "test header"}, ttl=1000)

~/.pyenv/versions/polly_venv/lib/python3.5/site-packages/webpush/utils.py in send_notification_to_user(user, payload, ttl)
     11     push_infos = user.webpush_info.select_related("subscription")
     12     for push_info in push_infos:
---> 13         _send_notification(push_info.subscription, payload, ttl)
     14 
     15 

~/.pyenv/versions/polly_venv/lib/python3.5/site-packages/webpush/utils.py in _send_notification(subscription, payload, ttl)
     44 
     45     try:
---> 46         req = webpush(subscription_info=subscription_data, data=payload, ttl=ttl, **vapid_data)
     47         return req
     48     except WebPushException as e:

~/.pyenv/versions/polly_venv/lib/python3.5/site-packages/pywebpush/__init__.py in webpush(subscription_info, data, vapid_private_key, vapid_claims, content_encoding, curl, timeout, ttl)
    440         content_encoding=content_encoding,
    441         curl=curl,
--> 442         timeout=timeout,
    443     )
    444     if not curl and response.status_code > 202:

~/.pyenv/versions/polly_venv/lib/python3.5/site-packages/pywebpush/__init__.py in send(self, data, headers, ttl, gcm_key, reg_id, content_encoding, curl, timeout)
    296         headers = CaseInsensitiveDict(headers)
    297         if data:
--> 298             encoded = self.encode(data, content_encoding)
    299             if "crypto_key" in encoded:
    300                 # Append the p256dh to the end of any existing crypto-key

~/.pyenv/versions/polly_venv/lib/python3.5/site-packages/pywebpush/__init__.py in encode(self, data, content_encoding)
    212                 dh=self.receiver_key,
    213                 auth_secret=self.auth_key,
--> 214                 version=content_encoding)
    215             reply = CaseInsensitiveDict({
    216                 'body': encrypted

~/.pyenv/versions/polly_venv/lib/python3.5/site-packages/http_ece/__init__.py in encrypt(content, salt, key, private_key, dh, auth_secret, keyid, keylabel, rs, version)
    393         print(type(content))  # dict
    394         result += encrypt_record(key_, nonce_, counter,
--> 395                                  content[i:i + chunk_size],
    396                                  (i + chunk_size) >= end)
    397         counter += 1

TypeError: unhashable type: 'slice'
```
It means that payloads need convert into string type then into bytes. But its dict. 
What did i wrong? Help please

**Comment by safwanrahman** [comment]
Can you update your python version? maybe the python version is not supported

**Comment by kintawer** [comment]
> Can you update your python version? maybe the python version is not supported

I dont know but it works if I send payloads with json convertation like this:
```python
send_notification_to_user(user=user, payload=json.dumps({"head": head, "body": body, "icon": ""}), ttl=1000)
```

**Comment by abiiranathan** [comment]
I ran into the same problem. Why is @safwanrahman bashing a gentleman with a genuine concern. 
The push message is sent only if you jsonify the payload. Problem is the pushEvent.data object is empty.

**Comment by safwanrahman** [comment]
@abiiranathan First of all, I am not bashing anyone. How do you blame anyone for that?

For your and @kintawer concern, the API that you are using is not a public API and is not documented anywhere. You should use `send_user_notification` instead.
