### ISSUE TITLE
js error in chrome 

### ISSUE THREAD

**Issue by akashvs232** [safwanrahman/django-webpush#83]
webpush.js:10 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at webpush.js:10

**Comment by safwanrahman** [comment]
@akashvs232 Do you have the button in your html?

**Comment by akashvs232** [comment]
yes i have .

**Comment by akashvs232** [comment]
here i also find the some error in my production server .
in local server working perfectly .
please try to solve out .

**Comment by safwanrahman** [comment]
@akashvs232 I think you are using
