### ISSUE TITLE
Subscription error. DOMException: Registration failed - permission denied.

### ISSUE THREAD

**Issue by lk-geimfari** [safwanrahman/django-webpush#90]
I've configured `django-web push` following steps from the readme, but I'm getting this when clicking on the `Subscribe` button.

<img width="781" alt="Screenshot 2020-12-02 at 13 58 33" src="https://user-images.githubusercontent.com/15812620/100864051-81b0df80-34a6-11eb-8f61-6bb3dee96412.png">

Any ideas what I'm doing wrong?

**Comment by rturket** [comment]
Try to go on Settings of your browser and search for permissions, there you will see notifications settings and maybe its because its blocked for the domain you are trying to reach.

**Comment by lk-geimfari** [comment]
@rturket Thanks! It helped.
