### ISSUE TITLE
webpush.models.SubscriptionInfo.MultipleObjectsReturned: get() returned more than one SubscriptionInfo -- it returned 2!

### ISSUE THREAD

**Issue by DesarrolladorTranseop** [safwanrahman/django-webpush#91]
Hi:

 I have this error. 
 
 **webpush.models.SubscriptionInfo.MultipleObjectsReturned: get() returned more than one SubscriptionInfo -- it returned 2!** 
 
 To be honest, I do not know when it happen, I mean, I do not have any patron. 
Sometimes happen when I push the button Enable or Disable ( {% webpush_button %} )

For some reason, it save the register two times in DataBase. 

I duplicated the template webpush_button.html and webpush.js for change the Strings in buttons, but If I delete them, It is happen again.

**Comment by safwanrahman** [comment]
Interesting! I need to check it!

**Comment by Tyilo** [comment]
A way to reproduce this (with the same `SubscriptionInfo`):
- Subscribe while not being logged in to a group `foo`
- Subscribe while being logged as `bar` in to a group `foo`
- (Again) Unsubscribe while being logged as `bar` in to a group `foo`

**Comment by safwanrahman** [comment]
@Tyilo Thanks for the STR. Can you come up with any patch? I am going by a rough time so can not promise any patch soon! 😓

**Comment by Tyilo** [comment]
@safwanrahman Done.
