### ISSUE TITLE
Javascript Error in Safari (undefined is not an object)

### ISSUE THREAD

**Issue by DesarrolladorTranseop** [safwanrahman/django-webpush#92]
Hi, I have a error in **Safari** when I push the button to suscribe. 

 TypeError: undefined is not an object (evaluating 'reg.pushManager.getSuscription')
   -suscribe
   -Anonymus Function

**Comment by camilodestacame** [comment]
Safari is not compatible with push api

**Comment by safwanrahman** [comment]
😓 Safari does not support push yet!
